apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fraud-detection.fullname" . }}-config
  labels:
    {{- include "fraud-detection.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.fraudApi.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
