{{- if .Values.fraudApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-detection.fullname" . }}-api
  labels:
    {{- include "fraud-detection.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.fraudApi.service.type }}
  ports:
    - port: {{ .Values.fraudApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fraud-detection.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
